import 'modern-css-reset/dist/reset.min.css';
import './globals.css';

import type { Metadata } from 'next';

import { notoSansJp } from './_ui/fonts';

/** @type {Metadata} metadata */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Layout
 * @param {React.ReactNode} children
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={notoSansJp.variable}>
      <body>{children}</body>
    </html>
  );
}
