/**
 * Query Key
 */
export const QUERY_KEYS = {
  SCHEDULE_SEARCH_RESULT: 'SCHEDULE_SEARCH_RESULT' as const,
  COMPANY_SEARCH_RESULT: 'COMPANY_SEARCH_RESULT' as const,
  SHOP_SEARCH_RESULT: 'SHOP_SEARCH_RESULT' as const,
  ORDER_SEARCH_RESULT: 'ORDER_SEARCH_RESULT' as const,
  USER_SEARCH_RESULT: 'USER_SEARCH_RESULT' as const,
  SHOP_DETAIL_INIT: 'SHOP_DETAIL_INIT' as const,
  ORDER_DETAIL_INIT: 'ORDER_DETAIL_INIT' as const,
  USER_DETAIL_INIT: 'USER_DETAIL_INIT' as const,
  DECISION_INIT: 'DECISION_INIT' as const,
  /** 承認待ちユーザー数取得 */
  WAITING_APPROVAL_SEARCH_RESULT: 'WAITING_APPROVAL_SEARCH_RESULT' as const,
};
